import {
  // Arrows
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowBigUp,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUpDash,
  ArrowBigDownDash,
  ArrowBigLeftDash,
  ArrowBigRightDash,
  ArrowLeftRight,
  ArrowUpDown,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveUpRight,
  MoveDownLeft,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  Undo2,
  Redo2,
  RotateCw,
  RotateCcw,
  Reply,
  Forward,
  // Bubbles & callouts
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessageSquareDashed,
  MessageCircleMore,
  MessageCircleQuestion,
  Quote,
  Megaphone,
  // Geometry
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Diamond,
  Dot,
  // Stars & sparkles
  Star,
  Sparkles,
  Sparkle,
  // Banners, badges, markers
  Flag,
  FlagTriangleLeft,
  FlagTriangleRight,
  Shield,
  ShieldCheck,
  Bookmark,
  Award,
  BadgeCheck,
  Tag,
  Tags,
  Medal,
  Trophy,
  Ribbon,
  // Marks
  Check,
  CheckCheck,
  X,
  Plus,
  Minus,
  // Nature & sky
  Sun,
  Moon,
  Cloud,
  CloudSun,
  CloudRain,
  CloudSnow,
  Rainbow,
  Snowflake,
  Droplet,
  Droplets,
  Flame,
  Wind,
  Mountain,
  // Plants
  Sprout,
  Leaf,
  Flower,
  Flower2,
  Shrub,
  Trees,
  TreePine,
  TreeDeciduous,
  // Animals
  Cat,
  Dog,
  Bird,
  Fish,
  Rabbit,
  Turtle,
  Bug,
  Snail,
  Squirrel,
  Footprints,
  // Food
  Apple,
  Cherry,
  Banana,
  Carrot,
  Pizza,
  IceCream,
  Cookie,
  Cake,
  CakeSlice,
  Candy,
  Popcorn,
  Egg,
  // Vehicles
  Car,
  Bus,
  Bike,
  Ship,
  Plane,
  Rocket,
  Train,
  Truck,
  // Celebration & emotion
  Heart,
  Gift,
  Crown,
  Gem,
  PartyPopper,
  Smile,
  Laugh,
  Frown,
  Hand,
  ThumbsUp,
  ThumbsDown,
  // Story & creativity
  Book,
  BookOpen,
  Pencil,
  Brush,
  Music,
  Music2,
  Guitar,
  Paintbrush,
  // Adventure & misc
  Anchor,
  Lightbulb,
  Key,
  Compass,
  Map,
  Umbrella,
  Tent,
  House,
  Castle,
  Shirt,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  // Kebab-case name used for search and as the stored iconName on shape layers.
  name: string;
  category: string;
  Component: LucideIcon;
}

// Category order controls display order in the sidebar.
export const ICONS: IconEntry[] = [
  // Arrows — the Canva-ish primitives the user asked for
  { name: "arrow-up", category: "Arrows", Component: ArrowUp },
  { name: "arrow-down", category: "Arrows", Component: ArrowDown },
  { name: "arrow-left", category: "Arrows", Component: ArrowLeft },
  { name: "arrow-right", category: "Arrows", Component: ArrowRight },
  { name: "arrow-up-left", category: "Arrows", Component: ArrowUpLeft },
  { name: "arrow-up-right", category: "Arrows", Component: ArrowUpRight },
  { name: "arrow-down-left", category: "Arrows", Component: ArrowDownLeft },
  { name: "arrow-down-right", category: "Arrows", Component: ArrowDownRight },
  { name: "arrow-big-up", category: "Arrows", Component: ArrowBigUp },
  { name: "arrow-big-down", category: "Arrows", Component: ArrowBigDown },
  { name: "arrow-big-left", category: "Arrows", Component: ArrowBigLeft },
  { name: "arrow-big-right", category: "Arrows", Component: ArrowBigRight },
  { name: "arrow-big-up-dash", category: "Arrows", Component: ArrowBigUpDash },
  { name: "arrow-big-down-dash", category: "Arrows", Component: ArrowBigDownDash },
  { name: "arrow-big-left-dash", category: "Arrows", Component: ArrowBigLeftDash },
  { name: "arrow-big-right-dash", category: "Arrows", Component: ArrowBigRightDash },
  { name: "arrow-left-right", category: "Arrows", Component: ArrowLeftRight },
  { name: "arrow-up-down", category: "Arrows", Component: ArrowUpDown },
  { name: "move-up", category: "Arrows", Component: MoveUp },
  { name: "move-down", category: "Arrows", Component: MoveDown },
  { name: "move-left", category: "Arrows", Component: MoveLeft },
  { name: "move-right", category: "Arrows", Component: MoveRight },
  { name: "move-up-right", category: "Arrows", Component: MoveUpRight },
  { name: "move-down-left", category: "Arrows", Component: MoveDownLeft },
  { name: "chevron-up", category: "Arrows", Component: ChevronUp },
  { name: "chevron-down", category: "Arrows", Component: ChevronDown },
  { name: "chevron-left", category: "Arrows", Component: ChevronLeft },
  { name: "chevron-right", category: "Arrows", Component: ChevronRight },
  { name: "chevrons-up", category: "Arrows", Component: ChevronsUp },
  { name: "chevrons-down", category: "Arrows", Component: ChevronsDown },
  { name: "chevrons-left", category: "Arrows", Component: ChevronsLeft },
  { name: "chevrons-right", category: "Arrows", Component: ChevronsRight },
  { name: "corner-up-left", category: "Arrows", Component: CornerUpLeft },
  { name: "corner-up-right", category: "Arrows", Component: CornerUpRight },
  { name: "corner-down-left", category: "Arrows", Component: CornerDownLeft },
  { name: "corner-down-right", category: "Arrows", Component: CornerDownRight },
  { name: "undo", category: "Arrows", Component: Undo2 },
  { name: "redo", category: "Arrows", Component: Redo2 },
  { name: "rotate-cw", category: "Arrows", Component: RotateCw },
  { name: "rotate-ccw", category: "Arrows", Component: RotateCcw },
  { name: "reply", category: "Arrows", Component: Reply },
  { name: "forward", category: "Arrows", Component: Forward },

  // Bubbles & callouts
  { name: "message-circle", category: "Bubbles", Component: MessageCircle },
  { name: "message-square", category: "Bubbles", Component: MessageSquare },
  { name: "message-square-text", category: "Bubbles", Component: MessageSquareText },
  { name: "message-square-dashed", category: "Bubbles", Component: MessageSquareDashed },
  { name: "message-circle-more", category: "Bubbles", Component: MessageCircleMore },
  { name: "message-circle-question", category: "Bubbles", Component: MessageCircleQuestion },
  { name: "quote", category: "Bubbles", Component: Quote },
  { name: "megaphone", category: "Bubbles", Component: Megaphone },

  // Geometry
  { name: "square", category: "Geometry", Component: Square },
  { name: "circle", category: "Geometry", Component: Circle },
  { name: "triangle", category: "Geometry", Component: Triangle },
  { name: "hexagon", category: "Geometry", Component: Hexagon },
  { name: "octagon", category: "Geometry", Component: Octagon },
  { name: "diamond", category: "Geometry", Component: Diamond },
  { name: "dot", category: "Geometry", Component: Dot },

  // Stars & sparkles
  { name: "star", category: "Stars", Component: Star },
  { name: "sparkles", category: "Stars", Component: Sparkles },
  { name: "sparkle", category: "Stars", Component: Sparkle },

  // Banners, badges, markers
  { name: "flag", category: "Banners", Component: Flag },
  { name: "flag-triangle-left", category: "Banners", Component: FlagTriangleLeft },
  { name: "flag-triangle-right", category: "Banners", Component: FlagTriangleRight },
  { name: "shield", category: "Banners", Component: Shield },
  { name: "shield-check", category: "Banners", Component: ShieldCheck },
  { name: "bookmark", category: "Banners", Component: Bookmark },
  { name: "award", category: "Banners", Component: Award },
  { name: "badge-check", category: "Banners", Component: BadgeCheck },
  { name: "tag", category: "Banners", Component: Tag },
  { name: "tags", category: "Banners", Component: Tags },
  { name: "medal", category: "Banners", Component: Medal },
  { name: "trophy", category: "Banners", Component: Trophy },
  { name: "ribbon", category: "Banners", Component: Ribbon },

  // Marks
  { name: "check", category: "Marks", Component: Check },
  { name: "check-check", category: "Marks", Component: CheckCheck },
  { name: "x", category: "Marks", Component: X },
  { name: "plus", category: "Marks", Component: Plus },
  { name: "minus", category: "Marks", Component: Minus },
  { name: "zap", category: "Marks", Component: Zap },

  // Nature & sky
  { name: "sun", category: "Nature", Component: Sun },
  { name: "moon", category: "Nature", Component: Moon },
  { name: "cloud", category: "Nature", Component: Cloud },
  { name: "cloud-sun", category: "Nature", Component: CloudSun },
  { name: "cloud-rain", category: "Nature", Component: CloudRain },
  { name: "cloud-snow", category: "Nature", Component: CloudSnow },
  { name: "rainbow", category: "Nature", Component: Rainbow },
  { name: "snowflake", category: "Nature", Component: Snowflake },
  { name: "droplet", category: "Nature", Component: Droplet },
  { name: "droplets", category: "Nature", Component: Droplets },
  { name: "flame", category: "Nature", Component: Flame },
  { name: "wind", category: "Nature", Component: Wind },
  { name: "mountain", category: "Nature", Component: Mountain },

  // Plants
  { name: "sprout", category: "Plants", Component: Sprout },
  { name: "leaf", category: "Plants", Component: Leaf },
  { name: "flower", category: "Plants", Component: Flower },
  { name: "flower-2", category: "Plants", Component: Flower2 },
  { name: "shrub", category: "Plants", Component: Shrub },
  { name: "trees", category: "Plants", Component: Trees },
  { name: "tree-pine", category: "Plants", Component: TreePine },
  { name: "tree-deciduous", category: "Plants", Component: TreeDeciduous },

  // Animals
  { name: "cat", category: "Animals", Component: Cat },
  { name: "dog", category: "Animals", Component: Dog },
  { name: "bird", category: "Animals", Component: Bird },
  { name: "fish", category: "Animals", Component: Fish },
  { name: "rabbit", category: "Animals", Component: Rabbit },
  { name: "turtle", category: "Animals", Component: Turtle },
  { name: "bug", category: "Animals", Component: Bug },
  { name: "snail", category: "Animals", Component: Snail },
  { name: "squirrel", category: "Animals", Component: Squirrel },
  { name: "footprints", category: "Animals", Component: Footprints },

  // Food
  { name: "apple", category: "Food", Component: Apple },
  { name: "cherry", category: "Food", Component: Cherry },
  { name: "banana", category: "Food", Component: Banana },
  { name: "carrot", category: "Food", Component: Carrot },
  { name: "pizza", category: "Food", Component: Pizza },
  { name: "ice-cream", category: "Food", Component: IceCream },
  { name: "cookie", category: "Food", Component: Cookie },
  { name: "cake", category: "Food", Component: Cake },
  { name: "cake-slice", category: "Food", Component: CakeSlice },
  { name: "candy", category: "Food", Component: Candy },
  { name: "popcorn", category: "Food", Component: Popcorn },
  { name: "egg", category: "Food", Component: Egg },

  // Vehicles
  { name: "car", category: "Vehicles", Component: Car },
  { name: "bus", category: "Vehicles", Component: Bus },
  { name: "bike", category: "Vehicles", Component: Bike },
  { name: "ship", category: "Vehicles", Component: Ship },
  { name: "plane", category: "Vehicles", Component: Plane },
  { name: "rocket", category: "Vehicles", Component: Rocket },
  { name: "train", category: "Vehicles", Component: Train },
  { name: "truck", category: "Vehicles", Component: Truck },

  // Celebration & emotion
  { name: "heart", category: "Celebration", Component: Heart },
  { name: "gift", category: "Celebration", Component: Gift },
  { name: "crown", category: "Celebration", Component: Crown },
  { name: "gem", category: "Celebration", Component: Gem },
  { name: "party-popper", category: "Celebration", Component: PartyPopper },
  { name: "smile", category: "Celebration", Component: Smile },
  { name: "laugh", category: "Celebration", Component: Laugh },
  { name: "frown", category: "Celebration", Component: Frown },
  { name: "hand", category: "Celebration", Component: Hand },
  { name: "thumbs-up", category: "Celebration", Component: ThumbsUp },
  { name: "thumbs-down", category: "Celebration", Component: ThumbsDown },

  // Story & creativity
  { name: "book", category: "Creativity", Component: Book },
  { name: "book-open", category: "Creativity", Component: BookOpen },
  { name: "pencil", category: "Creativity", Component: Pencil },
  { name: "brush", category: "Creativity", Component: Brush },
  { name: "paintbrush", category: "Creativity", Component: Paintbrush },
  { name: "music", category: "Creativity", Component: Music },
  { name: "music-2", category: "Creativity", Component: Music2 },
  { name: "guitar", category: "Creativity", Component: Guitar },

  // Adventure
  { name: "anchor", category: "Adventure", Component: Anchor },
  { name: "lightbulb", category: "Adventure", Component: Lightbulb },
  { name: "key", category: "Adventure", Component: Key },
  { name: "compass", category: "Adventure", Component: Compass },
  { name: "map", category: "Adventure", Component: Map },
  { name: "umbrella", category: "Adventure", Component: Umbrella },
  { name: "tent", category: "Adventure", Component: Tent },
  { name: "house", category: "Adventure", Component: House },
  { name: "castle", category: "Adventure", Component: Castle },
  { name: "shirt", category: "Adventure", Component: Shirt },
];

// Category display order — unique categories in the order they first appear.
export const ICON_CATEGORIES: string[] = Array.from(
  new Set(ICONS.map((i) => i.category))
);

// Flat lookup — used by the renderer to resolve a stored iconName.
export const ICON_LIBRARY: Record<string, LucideIcon> = Object.fromEntries(
  ICONS.map((i) => [i.name, i.Component])
);

export const ICON_NAMES: string[] = ICONS.map((i) => i.name);

export function getIcon(name: string): LucideIcon | null {
  return ICON_LIBRARY[name] ?? null;
}
